aot-fixer-pug:
  - packages/aot-fixer-pugl/**/*
diem-angular-util:
  - packages/diem-angular-util/**/*
diem-common:
  - packages/diem-common/**/*
diem-util:
  - packages/diem-util/**/*
diem-lib:
  - packages/diem-lib/**/*
diem-forms:
  - packages/diem-forms/**/*
aot-fixer:
  - packages/aot-fixer-pug/**/*
diem-spark:
  - applications/diem-spark/**/*
nodepy:
  - applications/diem-nodepy/**/*
diem-core:
  - applications/diem-core/**/*
diem-help:
  - applications/diem-help/**/*
diem-operator:
  - applications/diem-operator/**/*
diem-slack-bot:
  - applications/diem-slack-bot/**/*
workflow:
  - .github/**/*
repo:
  - ./*
