---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodepy
  namespace: default
  labels:
    app: nodepy
    tier: backend
    version: 0.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodepy
      tier: backend
  template:
    metadata:
      name: nodepy
      labels:
        app: nodepy
        tier: backend
        leap-common-redis-client: "true"
    spec:
      imagePullSecrets:
        - name: default-us-icr-io
      containers:
        - name: nodepy
          image: 127.0.0.1:30500/bizops/nodepy:latest
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          envFrom:
            - configMapRef:
                name: k8-bizops-config
            - secretRef:
                name: k8-bizops-secret
            - configMapRef:
                name: nodepy

          resources: {}
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "15"]
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
kind: Service
apiVersion: v1
metadata:
  name: nodepy
  namespace: default
  labels:
    app: nodepy
    tier: backend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8192
  selector:
    app: nodepy
    tier: backend
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
