apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.operator.name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version}}"
  annotations:
    {{- if .Values.controller.podAnnotations }}
    {{- with .Values.controller.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
data:
  NAMESPACE: {{ .Values.operator.config.NAMESPACE | quote }}