{{- if not .Values.base64 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.core.name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version}}"
  annotations:
    {{- if .Values.avp_path }}
    avp.kubernetes.io/path: {{ .Values.avp_path }}
    {{- end }}
    {{- if .Values.controller.podAnnotations }}
    {{- with .Values.controller.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
type: Opaque
stringData:
  SESSION__NAME: {{ .Values.core.secrets.SESSION_NAME  }}
  SESSION__SECRET: {{ .Values.core.secrets.SESSION_SECRET  }}
  {{- if .Values.mongodb.createservice }}
  MONGO__URL: {{ printf "mongodb://%s:%s@%s-mongodb:27017/%s" .Values.mongodb.auth.username .Values.mongodb.auth.password .Release.Name .Values.mongodb.auth.database  }}
  {{- else if .Values.core.secrets.MONGO_URL }}
  MONGO__URL: {{ .Values.core.secrets.MONGO_URL  }}
  {{- end }}
  {{- if .Values.core.secrets.MONGO_CA }}
  MONGO__CA: {{ .Values.core.secrets.MONGO_CA  }}
  {{- end }}
  {{- if .Values.core.secrets.SENDGRID_API }}
  SENDGRID__API: {{ .Values.core.secrets.SENDGRID_API  }}
  {{- end }}
  {{- if .Values.core.secrets.JWTTOKEN }}
  JWTTOKEN: {{ .Values.core.secrets.JWTTOKEN  }}
  {{- else }}
  JWTTOKEN: {{ uuidv4  }}
  {{- end }}
  {{- if .Values.core.auth.clientId }}
  CLIENT_ID: {{ .Values.core.auth.clientId  }}
  {{- end }}
  {{- if .Values.core.auth.clientSecret }}
  CLIENT_SECRET: {{ .Values.core.auth.clientSecret  }}
  {{- end }}
  {{- if .Values.core.config.s3.enabled }}
  COS__apiKeyId: {{ .Values.core.config.s3.apiKeyId  }}
  COS__endpoint: {{ .Values.core.config.s3.endpoint  }}
  COS__serviceInstanceId: {{ .Values.core.config.s3.serviceInstanceId  }}
  COS__signatureVersion: {{ .Values.core.config.s3.signatureVersion  }}
  {{- else if .Values.minio.createservice }}
  COS__accessKeyId: {{ .Values.minio.accessKey  }}
  COS__endpoint: {{ printf "http://%s-minio:9000" .Release.Name  }}
  COS__secretAccessKey: {{ .Values.minio.secretKey  }}
  COS__s3ForcePathStyle: "true"
  {{- end }}
  {{- if .Values.common.secrets.SLACKHOOK }}
  SLACKHOOK: {{ .Values.common.secrets.SLACKHOOK  }}
  {{- end }}
  {{- end }}
