{{- if .Values.help.createservice }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.help.name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version}}"
  annotations:
    {{- if .Values.controller.podAnnotations }}
    {{- with .Values.controller.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
data:
  APPPATH: {{ .Values.help.config.APPPATH | quote }}
  {{- if .Values.help.config.slack.enabled }}
  {{- with .Values.help.config.slack }}
  SLACK__EMOJI: {{ .SLACK_EMOJI | quote | indent 4}}
  SLACK__DEPLOY__CHANNEL: {{ .SLACK_DEPLOY_CHANNEL | quote }}
  SLACK__DEPLOY__USERNAME: {{ .SLACK_DEPLOY_USERNAME | quote }}
  SLACK__INTERNAL__CHANNEL: {{ .SLACK_INTERNAL_CHANNEL | quote }}
  SLACK__INTERNAL__USERNAME: {{ .SLACK_INTERNAL_USERNAME | indent 4}}
  {{- end }}
  {{- end }}
  {{- end }}