apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.common.config.diemAdmin }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version}}"
rules:
# Just an example, feel free to change it
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.common.config.diemAdminRbac }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.common.config.diemAdmin }}
  apiGroup: rbac.authorization.k8s.io