apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nodepy.configmapref }}
  namespace: {{ .Release.Namespace }}
data:
  PORT: {{ .Values.nodepy.targetPort | quote }}
  APPPATH: {{ .Values.core.config.APPPATH | quote }}
  {{- if .Values.core.config.slack.enabled }}
  {{- with .Values.core.config.slack }}
  SLACK__EMOJI: {{ .SLACK_EMOJI | quote | indent 4}}
  SLACK__DEPLOY__CHANNEL: {{ .SLACK_DEPLOY_CHANNEL | quote }}
  SLACK__DEPLOY__USERNAME: {{ .SLACK_DEPLOY_USERNAME | quote }}
  SLACK__INTERNAL__CHANNEL: {{ .SLACK_INTERNAL_CHANNEL | quote }}
  SLACK__INTERNAL__USERNAME: {{ .SLACK_INTERNAL_USERNAME | indent 4}}
  SLACK__USER__CHANNEL: {{ .SLACK_USER_CHANNEL | quote | indent 4}}
  SLACK__USER__USERNAME: {{ .SLACK_USER_USERNAME | quote }}
  {{- end }}
  {{- end }}
