{{- $service := printf "%s-%s-lb" .Release.Name .Values.nats.name -}}
{{- $ip := printf "%s-%s-lb" .Release.Name .Values.nats.name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.common.name }}-config
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook-weight: "5"
    helm.sh/hook: post-install,post-upgrade
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version}}"
data:
  K8_INSTANCE: {{ .Values.common.config.K8_INSTANCE }}
  K8_SYSTEM: {{ .Values.common.config.K8_SYSTEM }}
  K8_SYSTEM_NAME: {{ .Values.common.config.K8_SYSTEM_NAME }}
  K8_APPURLSHORT: {{ .Values.ingress.host }}
  {{- if .Values.nats.auth.user }}
  NATS__USER: {{ .Values.nats.auth.user | quote }}
  {{- end }}
  {{- if .Values.nats.clusterAuth.user }}
  NATS__CLUSTERUSER: {{ .Values.nats.clusterAuth.user | quote }}
  {{- end }}
  NATS__IP: {{ printf "%s-%s-client" .Release.Name .Values.nats.name }}
