# 23-05-2021
FROM gcr.io/spark-operator/spark-operator:v1beta2-1.2.3-3.1.1

LABEL   maintainer=guy_huinen@be.ibm.com \
        org.label-schema.description="Spark Operator Image for Diem" \
        org.label-schema.name="spark-operator" \
        org.label-schema.version=$BUILD_VERSION

ARG BUILD_DATE
LABEL org.label-schema.build-date=$BUILD_DATE

COPY jars/stocator-1.1.3.jar /opt/cos/
