# v3.0.0_2021-02-25_1
FROM quay.io/diem/base-pyspark:3.0.0

LABEL   maintainer=guy_huinen@be.ibm.com \
        org.label-schema.description="Spark Image for Diem" \
        org.label-schema.name="spark" \
        org.label-schema.version=$BUILD_VERSION

ARG BUILD_DATE
LABEL org.label-schema.build-date=$BUILD_DATE

COPY jars/* /opt/spark/jars/

WORKDIR /opt/

# For spark 3 we need t install them as root and then switch back

USER root

RUN python3.7 -m pip install --upgrade pip

COPY requirements-3.0.0.txt $HOME
RUN python3.7 -m pip install -r requirements-3.0.0.txt

RUN chmod -R 775 .

# USER 185


