# This is a basic workflow to help you get started with Actions

name: CI diem-default

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    paths:
      - "*"
      - ".github/**"
  pull_request:
    branches: [main]
    paths:
      - "*"
      - ".github/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: "Send Message to Slack"
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "G01NVSH7QP9"
          payload: |
            {
              "text": "Deployment started (In Progress)",
              "attachments": [
                {
                  "pretext": "Deployment started",
                  "color": "${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning'",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Completed"
                    },
                    {
                      "title": "Repository",
                      "short": false,
                      "value": "<${{ github.repository }}|${{ github.repositoryUrl }}>"
                    }, {
                      "title": "Ref",
                      "short": false,
                      "value": "${{ github.ref }}"
                    }, {
                      "title": "Commit",
                      "short": false,
                      "value": "<${{ github.event.head_commit.url }}|${{ github.sha }}>"
                    }, {
                      "title": "Author",
                      "short": false,
                      "value": "${{ github.event.head_commit.author.name }}"
                    }, {
                      "title": "Message",
                      "short": false,
                      "value": "${{ github.event.head_commit.message }}"
                    }, {
                      "title": "Workflow",
                      "short": false,
                      "value": "<${{ github.event.repository.html_url }}/actions/runs/${{ github.runId }}|${{ github.workflow }}>"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
        if: always()
